#!/usr/bin/env/python
import sys
import sqlite3
import os

MainCreateStatement = """
CREATE TABLE IF NOT EXISTS MainTable (
EntryNumber INTEGER PRIMARY KEY,
AdID INTEGER,
JSON_name VARCHAR(100),
FileName VARCHAR(100),
StartDate VARCHAR(100),
EndDate VARCHAR(100),
Impressions INTEGER,
Clicks INTEGER,
Spent VARCHAR(100),
AdText VARCHAR(100),
ImageText VARCHAR(100),
HashTags VARCHAR(100),
AdLandingPage VARCHAR(100),
CustomIncludes VARCHAR(100),
Junk VARCHAR(100),
AT_Placements VARCHAR(100),
AT_Age VARCHAR(100),
AT_Location VARCHAR(100),
AT_Language VARCHAR(100),
AT_Loose VARCHAR(100),
AT_Gender VARCHAR(100),
AT_PM_All VARCHAR(100),
AT_PM_Behaviors VARCHAR(100),
AT_PM_FieldOfStudy VARCHAR(100),
AT_PM_Politics VARCHAR(100),
AT_PM_Interests VARCHAR(100),
AT_PM_FriendsOfConnections VARCHAR(100),
AT_PM_MulticulturalAffinity VARCHAR(100),
AT_PM_PeopleWhoLike VARCHAR(100),
AT_PM_Industry VARCHAR(100),
AT_PM_Employers VARCHAR(100),
AT_AM_All VARCHAR(100),
AT_AM_Interests VARCHAR(100),
AT_AM_Politics VARCHAR(100),
AT_AM_Behaviors VARCHAR(100),
AT_AM_MulticulturalAffinity VARCHAR(100),
AT_AM_Industry VARCHAR(100),
AT_AM_Employers VARCHAR(100),
AT_EC_All VARCHAR(100),
AT_EC_ExcludePeopleWhoLike VARCHAR(100),
AT_EC_ExcludePeopleWhoAreGoingTo VARCHAR(100),
AT_EX_All VARCHAR(100),
AT_EX_MulticulturalAffinity VARCHAR(100),
AT_EX_Behaviors VARCHAR(100),
avgWordLength INTEGER);"""

PhotoCollectionCreateStatement = '''
CREATE TABLE IF NOT EXISTS PhotoCollection (AdID INTEGER PRIMARY KEY UNIQUE, photo BLOB);'''

BinaryFlagCreateStatements = [
'CREATE TABLE IF NOT EXISTS BlackCulture (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS BlueLives (AdID INTEGER PRIMARY KEY UNIQUE,Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS Refugees (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS Texas (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS SouthernCulture (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS Seperatist (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS Muslim (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS Christian (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS LGBTQ (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS NativeAmerican (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS RedPill (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS Patriot (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS LiberalFeminism (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS Veterans (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS SecondAmendment (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS Syria (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS Media (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS NewsAndEvents (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS Trump (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS Clinton (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS Sanders (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS otherCandidates (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS voterFraud (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS voterMisdirection (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);',
'CREATE TABLE IF NOT EXISTS voterTurnoutSuppression (AdID INTEGER PRIMARY KEY UNIQUE, Valence INTEGER NULL);']


def main():
      connection = sqlite3.connect("ReddFlag.db")
      cursor = connection.cursor()
      cursor.execute(MainCreateStatement)
      cursor.execute(PhotoCollectionCreateStatement)
      for x in BinaryFlagCreateStatements:
          cursor.execute(x)

if __name__ == '__main__':
    main()
